#!/usr/bin/env bash
# Create a local slice worktree with a prefilled .env.local port map.
#
# Usage:
#   ./scripts/new-slice-worktree.sh --slice P0-WEB-1 --slug app-shell
#   ./scripts/new-slice-worktree.sh --slice P0-API-1 --slug hono-skeleton --slot 2
#   ./scripts/new-slice-worktree.sh --slice P0-GEOM-1 --slug fastapi-skeleton --dry-run

set -euo pipefail

usage() {
  cat <<'EOF'
Create a slice worktree and prefill .env.local with unique local ports.

Required:
  --slice <ID>     Slice ID, e.g. P0-WEB-1
  --slug <name>    Short topic slug, e.g. app-shell

Optional:
  --slot <n>       Port slot (integer >= 1, default: auto from current worktree count)
  --branch <name>  Branch name (default: codex/<slice-lower>-<slug>)
  --path <dir>     Worktree directory (default: ../<repo>-<slice-lower>)
  --base <ref>     Base ref when creating new branch (default: main)
  --enter          Launch a new shell in the created worktree
  --force          Overwrite existing .env.local in worktree
  --dry-run        Print actions only; do not create anything
  -h, --help       Show this help
EOF
}

fail() {
  echo "Error: $*" >&2
  exit 1
}

to_slug() {
  echo "$1" \
    | tr '[:upper:]' '[:lower:]' \
    | sed -E 's/[^a-z0-9]+/-/g; s/^-+|-+$//g'
}

slice_id=""
topic_slug=""
slot=""
branch=""
worktree_path=""
base_ref="main"
enter_shell="false"
force_env="false"
dry_run="false"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --slice)
      [[ $# -ge 2 ]] || fail "--slice requires a value"
      slice_id="$2"
      shift 2
      ;;
    --slug)
      [[ $# -ge 2 ]] || fail "--slug requires a value"
      topic_slug="$2"
      shift 2
      ;;
    --slot)
      [[ $# -ge 2 ]] || fail "--slot requires a value"
      slot="$2"
      shift 2
      ;;
    --branch)
      [[ $# -ge 2 ]] || fail "--branch requires a value"
      branch="$2"
      shift 2
      ;;
    --path)
      [[ $# -ge 2 ]] || fail "--path requires a value"
      worktree_path="$2"
      shift 2
      ;;
    --base)
      [[ $# -ge 2 ]] || fail "--base requires a value"
      base_ref="$2"
      shift 2
      ;;
    --enter)
      enter_shell="true"
      shift
      ;;
    --force)
      force_env="true"
      shift
      ;;
    --dry-run)
      dry_run="true"
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      fail "Unknown argument: $1"
      ;;
  esac
done

[[ -n "$slice_id" ]] || fail "Missing required --slice"
[[ -n "$topic_slug" ]] || fail "Missing required --slug"

if ! [[ "$slice_id" =~ ^P[0-9]+-[A-Za-z0-9]+-[0-9]+$ ]]; then
  fail "Invalid --slice format. Expected pattern like P0-WEB-1"
fi

repo_root="$(git rev-parse --show-toplevel 2>/dev/null || true)"
[[ -n "$repo_root" ]] || fail "Not inside a git repository"
repo_name="$(basename "$repo_root")"

slice_slug="$(to_slug "$slice_id")"
topic_slug="$(to_slug "$topic_slug")"

if [[ -z "$slot" ]]; then
  worktree_count="$(git worktree list --porcelain | awk '/^worktree /{n++} END {print n+0}')"
  slot="$worktree_count"
fi

if ! [[ "$slot" =~ ^[0-9]+$ ]]; then
  fail "--slot must be an integer >= 1"
fi

if (( slot < 1 )); then
  fail "--slot must be >= 1 (slot 0 is reserved for the integration worktree)"
fi

if [[ -z "$branch" ]]; then
  branch="codex/${slice_slug}-${topic_slug}"
fi

if [[ -z "$worktree_path" ]]; then
  worktree_path="${repo_root}/../${repo_name}-${slice_slug}"
fi

web_port=$((5173 + slot))
api_port=$((3000 + slot))
geom_port=$((8000 + slot))

env_file="${worktree_path}/.env.local"

echo "Slice:        $slice_id"
echo "Branch:       $branch"
echo "Worktree:     $worktree_path"
echo "Base ref:     $base_ref"
echo "Port slot:    $slot"
echo "WEB/API/GEOM: ${web_port}/${api_port}/${geom_port}"
echo

run_cmd() {
  if [[ "$dry_run" == "true" ]]; then
    echo -n "[dry-run]"
    for arg in "$@"; do
      echo -n " \"$arg\""
    done
    echo
  else
    "$@"
  fi
}

if [[ -d "$worktree_path" ]]; then
  fail "Worktree path already exists: $worktree_path"
fi

if git show-ref --verify --quiet "refs/heads/$branch"; then
  run_cmd git -C "$repo_root" worktree add "$worktree_path" "$branch"
else
  run_cmd git -C "$repo_root" worktree add -b "$branch" "$worktree_path" "$base_ref"
fi

env_body="$(cat <<EOF
# Generated by scripts/new-slice-worktree.sh
# Slice: ${slice_id}
# Branch: ${branch}
# Port slot: ${slot}

WEB_PORT=${web_port}
API_PORT=${api_port}
GEOMETRY_PORT=${geom_port}

VITE_PORT=${web_port}
VITE_API_BASE_URL=http://localhost:${api_port}
VITE_GEOMETRY_BASE_URL=http://localhost:${geom_port}
API_BASE_URL=http://localhost:${api_port}
GEOMETRY_BASE_URL=http://localhost:${geom_port}
EOF
)"

if [[ "$dry_run" == "true" ]]; then
  echo "[dry-run] write ${env_file}:"
  echo "----------------------------------------"
  echo "$env_body"
  echo "----------------------------------------"
else
  if [[ -f "$env_file" && "$force_env" != "true" ]]; then
    fail "${env_file} already exists. Use --force to overwrite."
  fi
  printf '%s\n' "$env_body" > "$env_file"
fi

echo "Done."
echo "Next:"
echo "  cd \"$worktree_path\""
echo "  git status --short"
echo "  cat .env.local"

if [[ "$enter_shell" == "true" && "$dry_run" != "true" ]]; then
  echo
  echo "Opening shell in: $worktree_path"
  echo "Tip: type 'exit' to return."
  cd "$worktree_path"
  exec "${SHELL:-bash}" -l
fi
